// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type IsilandDocumentDataSlicesSlice = never;

/**
 * Content for Isiland documents
 */
interface IsilandDocumentData {
  /**
   * Slice Zone field in *Isiland*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: isiland.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<IsilandDocumentDataSlicesSlice> /**
   * Meta Description field in *Isiland*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: isiland.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Isiland*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: isiland.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Isiland*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: isiland.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Isiland document from Prismic
 *
 * - **API ID**: `isiland`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type IsilandDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<IsilandDocumentData>,
    "isiland",
    Lang
  >;

export type AllDocumentTypes = IsilandDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      IsilandDocument,
      IsilandDocumentData,
      IsilandDocumentDataSlicesSlice,
      AllDocumentTypes,
    };
  }
}
