// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  features: dynamic(() => import("./Features")),
  heading: dynamic(() => import("./HeadingSubmenu")),
  hero: dynamic(() => import("./Hero")),
  navigation_item: dynamic(() => import("./NavigationItem")),
  section_product: dynamic(() => import("./SectionProduct")),
  segment_picker: dynamic(() => import("./SegmentPicker")),
  showcase: dynamic(() => import("./Showcase")),
  sub_menu_item: dynamic(() => import("./SubMenuItem")),
  text_with_image: dynamic(() => import("./TextWithImage")),
};
